site_name: BambuQuickLearn
site_url: https://SwartzMss.github.io/BambuQuickLearn/
site_description: Bambu 学习笔记

nav:
  - 首页: index.md
  - 材料: materials/index.md
  - 打印机: printers/index.md
  - 打印技术: technologies/index.md
  - 切片软件: slicers/index.md
  - 设计: design/index.md
  - 故障排除: troubleshooting/index.md
  - 成品展示: showcase/index.md
theme:
  name: material
plugins:
  - search
